server:
  port: 9001
  
cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      access-key: <Access Key>
      secret-key: <Secret Key>
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/260086225865/TestQueue